version: 1
name: "My lovely gateway"
port: 8080
timeout: 10
cache_ttl: 3600

host:
  - "http://backend-service-1:80"
  - "http://backend-service-2:80"

endpoints:
  - endpoint: "/test"
    method: "GET"
    concurrent_calls: 1
    timeout: 1000
    cache_ttl: 3600
    backend:
      - host:
          - "http://backend-service-1:80"
          - "http://backend-service-2:80"
        url_pattern: "/"
        encoding: "json"
