security:
  # Authentication configuration
  auth:
    jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
    jwt_expiration: "24h"
    
    # API Keys (key -> client_id)
    api_keys:
      "api-key-123": "client-1"
      "api-key-456": "client-2"
      "api-key-789": "admin-client"
    
    # Basic Auth (username -> password)
    basic_auth:
      "admin": "admin123"
      "user": "user123"
    
    # Required roles for endpoints
    required_roles:
      "/admin/*": ["admin"]
      "/api/users": ["user", "admin"]
      "/api/sensitive": ["admin"]

  # Rate limiting configuration
  rate_limit:
    requests_per_second: 100
    burst_size: 200
    window_size: "1m"
    cleanup_interval: "5m"
    
    # Per-endpoint rate limits
    endpoints:
      "/api/auth/login":
        requests_per_second: 5
        burst_size: 10
        window_size: "1m"
      "/api/upload":
        requests_per_second: 10
        burst_size: 20
        window_size: "1m"

  # CORS configuration
  cors:
    allowed_origins:
      - "https://yourdomain.com"
      - "https://*.yourdomain.com"
      - "http://localhost:3000"  # Development
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "HEAD"
      - "PATCH"
    allowed_headers:
      - "Accept"
      - "Accept-Language"
      - "Content-Language"
      - "Content-Type"
      - "Authorization"
      - "X-API-Key"
      - "X-Client-ID"
      - "X-Signature"
      - "X-Timestamp"
      - "X-Request-ID"
    exposed_headers:
      - "X-RateLimit-Limit"
      - "X-RateLimit-Remaining"
      - "X-RateLimit-Reset"
      - "X-Request-ID"
    allow_credentials: true
    max_age: 86400  # 24 hours

  # Security headers configuration
  security_headers:
    content_type_nosniff: true
    frame_deny: true
    browser_xss_filter: true
    content_security_policy: "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'"
    referrer_policy: "strict-origin-when-cross-origin"
    hsts_max_age: 31536000  # 1 year
    hsts_include_subdomains: true
    hsts_preload: false

  # IP whitelist (optional)
  ip_whitelist:
    enabled: false
    allowed_ips:
      - "127.0.0.1"
      - "::1"
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"

  # Request signature authentication
  signature_auth:
    enabled: false
    secrets:
      "client-1": "secret-for-client-1"
      "client-2": "secret-for-client-2"

  # OAuth2 configuration (optional)
  oauth2:
    enabled: false
    client_id: "your-oauth2-client-id"
    client_secret: "your-oauth2-client-secret"
    redirect_url: "https://yourdomain.com/auth/callback"
    auth_url: "https://auth-provider.com/oauth/authorize"
    token_url: "https://auth-provider.com/oauth/token"
    user_info_url: "https://auth-provider.com/oauth/userinfo"

# Monitoring configuration
monitoring:
  # Metrics configuration
  metrics:
    enabled: true
    path: "/metrics"
    
  # Health check configuration
  health:
    enabled: true
    path: "/__health"
    readiness_path: "/__ready"
    liveness_path: "/__live"
    check_interval: "30s"
    check_timeout: "5s"

  # Tracing configuration (optional)
  tracing:
    enabled: false
    jaeger_endpoint: "http://jaeger:14268/api/traces"
    service_name: "porta-gateway"
    sample_rate: 0.1

# Logging configuration
logging:
  level: "INFO"
  format: "json"  # json or text
  output: "stdout"  # stdout, stderr, or file path
  
  # Request logging
  request_logging:
    enabled: true
    include_headers: false
    include_body: false
    exclude_paths:
      - "/__health"
      - "/__ready"
      - "/__live"
      - "/metrics"

# Circuit breaker configuration
circuit_breaker:
  enabled: true
  failure_threshold: 5
  recovery_timeout: "30s"
  timeout: "10s"

# Retry configuration
retry:
  enabled: true
  max_attempts: 3
  initial_interval: "100ms"
  max_interval: "1s"
  multiplier: 2.0 